For #9272 - Change reader mode link colors for better contrast ratio
mozilla-mobile/android-components pull request #12334
Opened 2022-06-15 12:58 UTC by Alexandru2909

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

2022-06-16 16:02 UTC, csadilek requested changes
Thanks for doing this! Light and Sepia themes have the same contrast ratio as desktop now, but dark theme doesn't yet in my testing. For easier testing (faster turnaround)s you can launch A-C's sample browser, which you can also quickly uninstall/install to make sure latest CSS changes are applied.

A second problem is that visited links aren't coloured correctly, see below.

Work is in progress to eventually replace this with the version we ship in Desktop (via GV), but good to fix this for now, so thanks again.

2022-06-17 10:08 UTC, Alexandru2909 commented on components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
> +  color: #45a1ff !important;
Thank you for reviewing!
It should now be applied, I removed the accidentally added space between `: is`. The contrast should be fine now.

2022-06-17 20:51 UTC, csadilek reviewed
Visited colours work now, but there's still a problem with the link colour in dark mode, see screenshot below.

2022-06-17 20:51 UTC, csadilek commented on components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
> +  color: #45a1ff !important;
I am still not seeing this colour applied in dark mode. It's still 0060df.
![Screenshot_20220617-164336](https://user-images.githubusercontent.com/472523/174399375-e797c0e2-fdd2-4b52-96ee-39e8b32e996e.png)

2022-06-20 06:37 UTC, Alexandru2909 commented on components/feature/readerview/src/main/assets/extensions/readerview/readerview.css
> +  color: #45a1ff !important;
I changed the `:not` attribute, the contrast is 6.34 for me now. Can you check again?

2022-06-20 14:24 UTC, csadilek approved these changes
Verified that contrast ratios match Desktop now, and visited links also work correctly now.

🚢

2022-06-20 14:38 UTC, merged