Bug 1796766 - Add support for silent web notifications
mozilla-mobile/android-components pull request #12987
Opened 2022-10-21 14:46 UTC by Alexandru2909

Add support for silent web notifications. The web notifications having the `silent` flag set will be assigned to a new channel.
Since a notification channel's priority can't be changed after it was created, this change will not enable sound on previously allowed notifications after update.

https://user-images.githubusercontent.com/35462038/197219989-13898183-1fc6-4054-bf3d-985eade48bfc.mp4

For the first notification, the default notification sound was played, the second notification was silent.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/android-components/blob/main/docs/changelog.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/main/android/accessibility_guide.md) or does not include any user facing features

### After merge
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in development.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.

### GitHub Automation

Used by GitHub Actions.

2022-10-21 14:49 UTC, Alexandru2909 commented
cc @lime124 Based on the discussion [here](https://mozilla-hub.atlassian.net/browse/FNXV2-9801) to confirm that making web notifications play the default notification sound is the intended change.

2022-10-25 02:35 UTC, jonalmeida requested changes
> Since a notification channel's priority can't be changed after it was created, this change will not enable sound on previously allowed notifications after update.

I don't think we should create a new notification channel just for silent notifications - this sounds like the wrong direction to take. We can change the default though _for new_ users who haven't had a notification channel created because they have had Web Notifications go out yet.

2022-10-25 02:36 UTC, jonalmeida commented on components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt
> +    val silent: Boolean = true,
Huh, thanks for adding this; didn't realize that it wasn't passed in here already.

2022-10-31 16:19 UTC, gabrielluong commented
Hey @Alexandru2909, We're just tidying up the PRs since this project moved to a new repository. It is now developed and maintained at: https://github.com/mozilla-mobile/firefox-android

2022-10-31 16:19 UTC, closed without merging