Introduce RegionManager to be used by RegionMiddleware
mozilla-mobile/android-components pull request #8595
Opened 2020-10-02 14:01 UTC by pocmo

First code for implementing RFC being discussed in #8437. Next step is adding the Middleware that uses RegionManager. And then the SearchMiddleware that uses the RegionState.

2020-10-02 18:45 UTC, csadilek requested changes
Looks great! A few nits and looks like there's a bug with the UPDATE_INTERVAL not being in MS when compared.

2020-10-02 18:45 UTC, csadilek commented on components/browser/state/src/main/java/mozilla/components/browser/state/search/RegionState.kt
> + * @param home The "home" region of the user, which will change slowly if the user stays in the same
nit: s/slowly/only ...or remove. Reading the docs of current made it clear though.

2020-10-02 18:45 UTC, csadilek commented on components/browser/state/src/main/java/mozilla/components/browser/state/search/RegionState.kt
> +        val Default = RegionState("xx", "xx")
nit: XX

2020-10-02 18:45 UTC, csadilek commented on components/support/test/src/main/java/mozilla/components/support/test/fakes/FakeClock.kt
> + * that can it invokes. In a test this lambda can be replaced by FakeClock()::time.
nit: that it can invoke?

2020-10-02 18:45 UTC, csadilek commented on components/support/test/src/main/java/mozilla/components/support/test/fakes/FakeSharedPreferences.kt
> + * A simple [SharedPreferences] implementation baked by an in-memory map. Helpful in unit tests and
nit: backed by.

2020-10-02 18:45 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
> +private const val UPDATE_INTERVAL = 60 * 60 * 24 * 14
nit: UPDATE_INTERVAL_IN_SECONDS, but see comment below. I think this was meant to be in MS as well and missing a `*1000`.

2020-10-02 18:45 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
> +private const val RETRY_TIMEOUT: Long = 10 * 60 * 1000
nit: RETRY_TIMEOUT_IN_MS

2020-10-02 18:45 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
> +                if (now > (firstSeen ?: 0) + UPDATE_INTERVAL) {
Looks like now/firstSeen/currentTime are in MS, but UPDATE_INTERVAL is in S right now.

2020-10-02 18:45 UTC, csadilek commented on components/feature/search/src/test/java/mozilla/components/feature/search/region/RegionManagerTest.kt
> +        clock.advanceBy(60 * 60 * 24 * 7)
See comment in file. This is not a week in ms, missing `*1000`.

2020-10-02 18:45 UTC, csadilek commented on components/feature/search/src/test/java/mozilla/components/feature/search/region/RegionManagerTest.kt
> +        clock.advanceBy(60 * 60 * 24 * 8)
Missing `*1000`.

2020-10-06 15:10 UTC, pocmo commented
@daleharvey Can you take a brief look at `RegionManager` in this PR? It's close to `region.jsm`.

2020-10-06 16:42 UTC, pocmo commented
@csadilek I added a commit with `RegionMiddleware` on top of the previous changes.

2020-10-06 17:22 UTC, csadilek approved these changes
Nice, looks good to me now! 🕙 🚢

2020-10-06 17:22 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionMiddleware.kt
> + * [Middleware] implementation for updating the
nit: updating the...

2020-10-06 17:22 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionMiddleware.kt
> +        if (action is InitAction) {
🎉

2020-10-06 17:22 UTC, csadilek commented on components/feature/search/src/main/java/mozilla/components/feature/search/region/RegionManager.kt
> +private const val UPDATE_INTERVAL_MS = 60 * 60 * 24 * 14 * 1000
nitnit: easier to read: 14 * 24 * 60 * 60 * 1000

2020-10-08 12:08 UTC, daleharvey commented
Sorry for the delay but these looks good to me, I like the tests here too, the mock timer is probably more robust than the desktop version that changes the interval to test

2020-10-08 13:39 UTC, merged